const testPhrases = [
  "a la derecha de mi mano",
  "dentro de casa",
  "después de comer",
  "hacia delante",
  "bajo las estrellas",
  "contra el coronavirus",
  "durante la sesión",
  "según lo que ha dicho",
  "sin palabras",
  "en diez minutos",
  "ante todo el mundo",
  "cabe muchas posibilidades",
  "con mucho cuidado",
  "entre nosotros",
  "hasta el final",
  "para los mayores",
  "mediante el barco",
  "por mí",
  "sobre las conversaciónes",
  "tras la tormenta",
  "vía el canal official",
  "el bueno versus el malo",
];

const expectedPhrases = [
  ['LA', 'DERECHA', 'MI', 'MANO'],
  ['CASA'],
  ['COMER'],
  ['DELANTE'],
  ['LA', 'ESTRELLA'],
  ['EL', 'CORONAVIRU'],
  ['LA', 'SESION'],
  ['LO', 'QUE', 'HA', 'DICHO'],
  ['PALABRA'],
  ['DIEZ', 'MINUTO'],
  ['TODO', 'EL', 'MUNDO'],
  ['MUCHA', 'POSIBILIDAD'],
  ['MUCHO', 'CUIDADO'],
  ['NOSOTRO'],
  ['EL', 'FINAL'],
  ['LO', 'MAYOR'],
  ['EL', 'BARCO'],
  ['MI'],
  ['LA', 'CONVERSACION'],
  ['LA', 'TORMENTA'],
  ['EL', 'CANAL', 'OFFICIAL'],
  ['EL', 'BUENO', 'EL', 'MALO']
];

const expectedInvertedPhrases = [
  ['ONAM', 'IM', 'AHCERED', 'AL'],
  ['ASAC'],
  ['REMOC'],
  ['ETNALED'],
  ['ALLERTSE', 'AL'],
  ['URIVANOROC', 'LE'],
  ['NOISES', 'AL'],
  ['OHCID', 'AH', 'EUQ', 'OL'],
  ['ARBALAP'],
  ['OTUNIM', 'ZEID'],
  ['ODNUM', 'LE', 'ODOT'],
  ['DADILIBISOP', 'AHCUM'],
  ['ODADIUC', 'OHCUM'],
  ['ORTOSON'],
  ['LANIF', 'LE'],
  ['ROYAM', 'OL'],
  ['OCRAB', 'LE'],
  ['IM'],
  ['NOICASREVNOC' ,'AL'],
  ['ATNEMROT', 'AL'],
  ['LAICIFFO', 'LANAC', 'LE'],
  ['OLAM', 'LE', 'ONEUB', 'LE' ]
];

module.exports = {
  expectedPhrases,
  expectedInvertedPhrases,
  testPhrases,
};
